### PR TITLE
Add a CI to XKCP, with native as well as cross-compilation tests (com…

### PR DESCRIPTION
**Pull request by rben-dev**
…pilation

and unit tests).

The rationale of the CI script is to:
- Cross-compile all the possible targets
- Run them using Qemu in user mode (for both x86 and native x86) or Wine (for native windows mingw cross-compilation).

Even the microcontrollers ARM Cortex-M variants are cross-compiled and tested (using Qemu in system mode and semi-hosting).

For now, only the `UnitTests -p` toggle is used as the `-a` toggle takes too much time.

The CI can be run independently from github runners as it is a dedicated Docker. Just run (with docker installed of course) at the root folder:

`$ CI_VERBOSE=1 make -f Makefile.ci`

(since native builds are executed with wine here, users of Mac M1 / ARM should expect some issues with these: future updates of the CI script could detect this and avoid Wine in this case. Anyway, CI should work on any x86 plarform).

### CODE REVIEW

**Comment by rben-dev** [comment]
This seems to be a similar work as PR #131 while adding cross-compilation and emulation tests. We should discuss the pros and cons of each approach and converge to a proper CI for XKCP.

**Comment by gvanas** [comment]
This looks great, thanks!!!

> AVX512 not supported yet by Qemu (and not supported by native CI CPUs)

In the K12 CI, the AVX512 tests are run properly, e.g., see this [job](https://github.com/XKCP/K12/actions/runs/6174641398/job/16759693065).

**Comment by rben-dev** [comment]
Thanks for the feedback regarding AVX512 :-) Indeed, I underestimated the native CPUs on github actions runners. I will patch the current CI to integrate this.

**Comment by rben-dev** [comment]
Well, this is really an interesting thing. The `/proc/cpuinfo` of the Github runner (see the image) does not exhibit AVX512 compatibility, while your `cpuid` assembly test from K12 seems to have the flags for `avx512vl` and `avx512f` set, and the runtime test does not crash ...
The `AMD Epyc 7763` wiki (https://en.wikichip.org/wiki/amd/epyc/7763#Expansions) does not seem to mention AVX512 neither ...

Do you have a clue of what is happening?

image

**Comment by gvanas** [comment]
The K12 test was run in September. Maybe it used a different processor at the time.

**Pull request merged**
