### PR TITLE
Usage documentation

### PR DESCRIPTION
**Pull request by hadielyakhni**
A documentation page showing in simple steps the way to use different cryptographic functions provided by XKCP in users' C code.

Todo:
- [x] Add examples of how to feed input in chunks, and squeeze output in chunks (for FIPS-202 functions)
- [x] Add examples for TurboSHAKE
- [x] Add examples for KangarooTwelve
- [x] Add examples for Kravatte and its modes
- [x] Add examples for Xoofff and its modes
- [x] Add examples for Xoodyak

### CODE REVIEW

**Comment by gvanas** [comment]
Very nice, thanks!

Minor comment: in the chunked input and output examples, can you add the `#include` preamble?

**Comment by gvanas** [comment]
Nice, thanks! This is taking shape. Let's wait for Kravatte, Xoofff and Xoodyak to be covered so that we can merge everything at once.

Note that there is no need to cover Ketje and Keyak, as these have been removed from XCKP.

**Comment by hadielyakhni** [comment]
Hello Prof @gvanas, I have added the examples to Xoodyak, and with this, the PR is ready for a final review :) 

Would it be interesting to add a few references to [the Xoodyak paper](https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/finalist-round/updated-spec-doc/xoodyak-spec-final.pdf) for curious readers to refer to?

**Comment by gvanas** [comment]
Hello @hadielyakhni .

Good work, this looks nice!

I just pushed some editorial changes. On top of that, I have a few more comments:

- TurboSHAKE128 is initialized with the general TurboSHAKE initialization function and c=256. This is fine, but maybe it would be easier to read if you'd use the specific macro `TurboSHAKE128_Initialize` instead.
- I am not sure about the examples of Kravatte and Xoofff without a mode. Using such a deck function alone is not very useful. I would suggest removing this example for now. In the long run, we can try to think about a more meaningful example, such as implementing one of the modes from our "Jammin' on the deck" paper (Asiacrypt 2022).
- In Xoodyak, you talk about chunks, but these are really distinct strings instead. In Xoodyak multiple input strings are separated, i.e., absorb(X) followed by absorb(Y) is not the same as absorb(X || Y). Similarly, multiple output strings are also separated, i.e., squeeze(len1) followed by squeeze(len2) is not the same as squeeze(len1+len2). In the former case, you are asking for two outputs that are unrelated (domain separated), while in the latter, this is one longer output.

After you address these three comments, your branch will be ready to be merged to master.

Kind regards,
Gilles Van Assche

**Comment by hadielyakhni** [comment]
Hello professor @gvanas , thanks for the feedback :)
I have pushed the required changes, please let me know if I missed something.

**Pull request merged**
